# Generated by Django 4.2.25 on 2025-10-12 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_provider', models.CharField(choices=[('aws', 'AWS WorkSpaces'), ('azure', 'Azure Virtual Desktop')], max_length=10)),
                ('credential_name', models.CharField(max_length=255)),
                ('access_key', models.TextField()),
                ('secret_key', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('directory_id', models.CharField(blank=True, max_length=255)),
                ('tenant_id', models.CharField(blank=True, max_length=255)),
                ('subscription_id', models.CharField(blank=True, max_length=255)),
                ('resource_group', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('provider_user', 'credential_name')},
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.CharField(blank=True, max_length=255)),
                ('cloud_provider', models.CharField(choices=[('aws', 'AWS WorkSpaces'), ('azure', 'Azure Virtual Desktop')], max_length=10)),
                ('workspace_type', models.CharField(choices=[('ubuntu', 'Ubuntu Linux'), ('windows', 'Windows')], max_length=20)),
                ('bundle_id', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('STOPPED', 'Stopped'), ('STOPPING', 'Stopping'), ('STARTING', 'Starting'), ('REBOOTING', 'Rebooting'), ('TERMINATED', 'Terminated'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('connection_string', models.TextField(blank=True)),
                ('username', models.CharField(max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='jobs.application')),
                ('cloud_credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspaces', to='workspaces.cloudcredential')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
