# Generated by Django 4.2.25 on 2025-11-15 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='password_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='registration_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='jobs.application'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='bundle_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
