# Generated by Django 4.2.25 on 2025-11-15 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_add_import_workspace_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='cloud_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workspaces', to='workspaces.cloudcredential'),
        ),
    ]
